### ISSUE TITLE
Getting error TypeError: Cannot read property 'headersSent' of undefined

### ISSUE THREAD

**Issue by duongdev** [moleculerjs/moleculer-apollo-server#5]
Hi guys, I just started getting this error today on my WIP project. I've tried to init a new project but it's still there. Not sure if it's an error of this package or `moleculer-web`. Please help.

## Reproduce

- Init a new project with `moleculer-cli`.
- Install this package by `npm install moleculerjs/moleculer-apollo-server moleculer-web graphql graphql-tag`.
- Update `api.service.js` like below:

```javascript
// api.service.js
const ApiGateway 	= require("moleculer-web");
const { ApolloService } = require("moleculer-apollo-server");
const gql = require("graphql-tag");

module.exports = {
	name: "api",

	mixins: [
		// Gateway
		ApiGateway,

		// GraphQL Apollo Server
		ApolloService({

			// Global GraphQL typeDefs
			typeDefs: gql`
				scalar Empty
				scalar Date

				type Query {
					id: String
				}
			`,

			// Global resolvers
			resolvers: {},

			// API Gateway route options
			routeOptions: {
				path: "/graphql",
				cors: true,
				mappingPolicy: "restrict"
			},

			// https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server.html
			serverOptions: {
				tracing: true,

				// engine: {
				// 	apiKey: process.env.APOLLO_ENGINE_KEY
				// }
			}
		})
	]
};
```
- ServiceBroker with 3 service(s) is started successfully.
```bash
➜  moleculer-demo npm run dev

> moleculer-demo@1.0.0 dev /Users/duongdev/Projects/duongdev/moleculer-demo
> moleculer-runner --repl --hot services

[2019-01-12T19:02:26.417Z] INFO  macbookpro.local-16126/BROKER: Moleculer v0.13.5 is starting...
[2019-01-12T19:02:26.419Z] INFO  macbookpro.local-16126/BROKER: Node ID: macbookpro.local-16126
[2019-01-12T19:02:26.420Z] INFO  macbookpro.local-16126/BROKER: Namespace: <not defined>
[2019-01-12T19:02:26.420Z] INFO  macbookpro.local-16126/REGISTRY: Strategy: RoundRobinStrategy
[2019-01-12T19:02:26.423Z] INFO  macbookpro.local-16126/BROKER: Serializer: JSONSerializer
[2019-01-12T19:02:26.424Z] INFO  macbookpro.local-16126/BROKER: Registered 10 internal middleware(s).
[2019-01-12T19:02:27.883Z] INFO  macbookpro.local-16126/API: Register route to '/graphql'
[2019-01-12T19:02:28.052Z] INFO  macbookpro.local-16126/API:   Alias: * /graphql/ -> <Function>
[2019-01-12T19:02:28.052Z] INFO  macbookpro.local-16126/API: Register route to '/'
[2019-01-12T19:02:28.052Z] INFO  macbookpro.local-16126/API: API Gateway created!
[2019-01-12T19:02:28.063Z] INFO  macbookpro.local-16126/REGISTRY: '$node' service is registered.
[2019-01-12T19:02:28.064Z] INFO  macbookpro.local-16126/API: 🚀 GraphQL server is available at /graphql
[2019-01-12T19:02:28.065Z] INFO  macbookpro.local-16126/REGISTRY: 'greeter' service is registered.
[2019-01-12T19:02:28.147Z] INFO  macbookpro.local-16126/API: API Gateway listening on http://0.0.0.0:3000
[2019-01-12T19:02:28.150Z] INFO  macbookpro.local-16126/REGISTRY: 'api' service is registered.
[2019-01-12T19:02:28.153Z] INFO  macbookpro.local-16126/BROKER: ServiceBroker with 3 service(s) is started successfully.
```
- Open http://0.0.0.0:3000/graphql.
- Got this error:
```bash
(node:15431) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headersSent' of undefined
    at Service.sendResponse (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/moleculer-web/src/index.js:515:12)
    at send (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/moleculer-apollo-server/src/ApolloServer.js:17:10)
    at Service.graphqlHandler (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/moleculer-apollo-server/src/ApolloServer.js:59:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:15431) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15431) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-01-12T18:52:50.447Z] WARN  macbookpro.local-15431/BROKER: Request 'api.rest' is timed out. { requestID: null, nodeID: 'macbookpro.local-15431', timeout: 10000 }
[2019-01-12T18:52:50.453Z] ERROR macbookpro.local-15431/API:    Request error! RequestTimeoutError : Request is timed out when call 'api.rest' action on 'macbookpro.local-15431' node.
 RequestTimeoutError: Request is timed out when call 'api.rest' action on 'macbookpro.local-15431' node.
    at p.timeout.catch.err (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/moleculer/src/middlewares/timeout.js:33:13)
    at tryCatcher (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/duongdev/Projects/duongdev/moleculer-demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
Data: { action: 'api.rest', nodeID: 'macbookpro.local-15431' }
[2019-01-12T18:52:50.454Z] INFO  macbookpro.local-15431/API: <= 504 GET / [+10.019 s]
[2019-01-12T18:52:50.454Z] INFO  macbookpro.local-15431/API:
```

ping @icebob or someone please help me on this issue asap.

**Comment by icebob** [comment]
Sure, I missed it :)
